### ISSUE TITLE
So it's a privacy exploit, but...

### ISSUE THREAD

**Issue by Qix-** [diracdeltas/sniffly#5]
It's something that is an extreme side effect of latency, if I'm not mistaken. I can't imagine a fix that doesn't include disabling caches or spoofing latency - both of which would have potentially adverse effects to the user.

Very interesting exploit, by the way.

**Comment by diracdeltas** [comment]
One interesting fix is https://trac.torproject.org/projects/tor/ticket/6458. If I understand correctly, this means that:
1. user visits ​https://thirdparty.com, gets HSTS pin
2. user visits ​http://example.com with <img src="​http://thirdparty.com">. the browser makes the request over HTTP anyway because the user has never visited thirdparty.com on example.com before.

**Comment by tejacques** [comment]
I don't think that's a great solution because it means an attacker can put an http:// link on their site and use that as an attack vector bypass the https:// upgrade when attempting to MITM your bank or something else.
